# Docker compose
version: "3.8"

# コンテナ (サーバ) の宣言
services:
  # 時間足の過去データなどなどを入れるデータベースコンテナ
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: always 
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_volume:/var/lib/postgresql/data
    env_file:
      - .env

  # データベースコンテナが起動するまで起動せず、他のサーバの起動をブロックするコンテナ
  wait-for-db:
    image: dadarek/wait-for-dependencies
    depends_on:
      - timescaledb
    command: timescaledb:5432  

  # Jupyter Labが動作する開発を行うコンテナ
  jupyter:
    build:
      context: ./jupyter
      args:
        - GIT_USER=${GIT_USER} # GIT_USERは事前にユーザー環境変数として設定しておく
        - GIT_EMAIL=${GIT_EMAIL} # GIT_EMAILは事前にユーザー環境変数として設定しておく
    image: jupyter-image
    container_name: jupyter
    restart: always
    depends_on:
      - wait-for-db
    ports:
      - "8888:8888" # Jupyter用ポート
      - "8050:8050" # Dash用ポート
    volumes:
      - jupyter_volume:/home/jovyan/work # /home/jovyan/workに以下のファイルしかディスクには保存されないことに注意
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
      - BINANCE_APIKEY=${BINANCE_APIKEY} # BINANCE_APIKEYは事前にユーザー環境変数として設定しておく
      - BINANCE_APISECRET=${BINANCE_APISECRET} # BINANCE_APISECRETは事前にユーザー環境変数として設定しておく
      - BINANCE_TESTNET_APIKEY=${BINANCE_TESTNET_APIKEY} # BINANCE_TESTNET_APIKEYは事前にユーザー環境変数として設定しておく
      - BINANCE_TESTNET_APISECRET=${BINANCE_TESTNET_APISECRET} # BINANCE_TESTNET_APISECRETは事前にユーザー環境変数として設定しておく
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK} # DISCORD_WEBHOOKは事前にユーザー環境変数として設定しておく
      - GIT_ACCESSTOKEN=${GIT_ACCESSTOKEN} # GIT_ACCSESTOKENは事前にユーザー環境変数として設定しておく
      - GIT_USER=${GIT_USER} # GIT_USERは事前にユーザー環境変数として設定しておく
      - GIT_EMAIL=${GIT_EMAIL} # GIT_EMAILは事前にユーザー環境変数として設定しておく
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK} # DISCORD_WEBHOOKは事前にユーザー環境変数として設定しておく
    env_file:
      - .env
    command: start-notebook.sh --NotebookApp.token='wannabebotter' --NotebookApp.notebook_dir='/home/jovyan/work'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always 
    ports:
      - "8889:8000"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    environment:
      - PGADMIN_LISTEN_PORT=8000
      - PGADMIN_DEFAULT_EMAIL=wannabebotter@wannabebotter.com
      - PGADMIN_DEFAULT_PASSWORD=wannabebotter
    
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
    restart: unless-stopped
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8890:8080"
    depends_on:
      - kafka
      - zookeeper
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181     
  
  ftp_server:
    image: stilliard/pure-ftpd:latest
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ftp_volume:/home/ftpusers
    environment:
      - PUBLICHOST=localhost
      - ADDED_FLAGS="--tls=2"
    env_file:
      - .env
    restart: unless-stopped

  mlflow:
    build: ./mlflow
    image: mlflow-image
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "8891:8890"
    command: mlflow server --host 0.0.0.0 --port 8890 --backend-store-uri "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/mlflow" --default-artifact-root "ftp://${FTP_USER_NAME}:${FTP_USER_PASS}@${FTP_HOST}/artifacts"

# 各コンテナが利用するディスクスペースの宣言
volumes:
  timescaledb_volume:
  jupyter_volume:
  pgadmin_volume:
  ftp_volume:
